default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test: &test
  adapter: sqlite3
  database: ":memory:"
  verbosity: silent



